Feature/uppsf 2103 accept version and revision
Financial-Times/nativerw pull request #57
Opened 2021-02-26 11:46 UTC by StephanZahariev

# Description

## What

Change native-rw to accept version and revision via PUT/PATCH

## Why

[UPPSF-2103](https://financialtimes.atlassian.net/browse/UPPSF-2103)

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [X] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-03-04 12:43 UTC, gotha requested changes

2021-03-04 12:43 UTC, gotha commented on cmd/nativerw/main.go
> +		ValidateHeader(resources.ContentRevisionHeader).
I don't think revision header is required for PATCH

2021-03-04 12:43 UTC, gotha commented on docker-compose.yml
> +version: '2'
the file is incorrectly formatted, it should be idented with 2 spaces.

2021-03-04 12:43 UTC, gotha commented on pkg/db/mongorw.go
>  	index := mgo.Index{
I think we should have 2 indices, one for uuid only and another one for uuid - content-revision pair.
But this is assumption on my side of the way Mongo works. We should check it

2021-03-04 12:43 UTC, gotha commented on pkg/resources/timestamp_creator.go
> +	return time.Now().Format("2006-01-02T15:04:05.999Z")
I assumed we are going to create actual Unix timestamp.

2021-03-04 12:43 UTC, gotha commented on cmd/nativerw/main.go
> +	r.HandleFunc("/{collection}/{resource}", resources.Filter(resources.WriteContent(mongo, &ts)).
can we reformat these like that:
```
	r.HandleFunc("/{collection}/{resource}",
		resources.Filter(resources.WriteContent(mongo, &ts)).
			ValidateAccess(mongo).
			CheckNativeHash(mongo).
			ValidateHeader(resources.SchemaVersionHeader).
			Build()).
		Methods("PUT")
```

2021-03-04 12:43 UTC, gotha commented on pkg/resources/patch.go
> +		w.Header().Add(SchemaVersionHeader, schemaVersion)
I am not sure why are we returning the version header here.
If anything, it makes more sense to return the revision

2021-03-04 12:43 UTC, gotha commented on pkg/resources/utils.go
>  	txID := req.Header.Get(txHeaderKey)
I think here we should use transactionidutils.GetTransactionIDFromRequest and get rid of the txHeaderKey constant

2021-03-04 12:43 UTC, gotha commented on pkg/resources/write.go
> +			fmt.Sprintf("Successfully saved, collection=%s, origin-system-id=%s schema-version=%s", collectionID, originSystemIDHeader, schemaVersion))
just suggestion for improvement. instead of using fmt.Sprintf, we can use log.WithField("collection", "value"), etc. ..

2021-03-04 13:01 UTC, StephanZahariev commented on pkg/db/mongorw.go
>  	index := mgo.Index{
I agree that we may need more indexes but lets check the real workload and see if there is a performance bottleneck.

2021-03-04 14:06 UTC, StephanZahariev commented on pkg/resources/patch.go
> +		w.Header().Add(SchemaVersionHeader, schemaVersion)
Since PATCH returns Json it makes sense to return also the schema version so the consumer is aware of the expected format.

Good catch about the revision. I will add it.

2021-03-05 14:55 UTC, gotha commented on pkg/resources/utils.go
> +	txHeaderKey = "X-Request-Id"
I think we should get rid of this constant. 
It is only used in hashing.go to extract tid, but it can be done with transactionidutils.

2021-03-08 11:08 UTC, gotha approved these changes

2021-03-08 11:28 UTC, merged