Feature/uppsf 2104 get to return latest version
Financial-Times/nativerw pull request #58
Opened 2021-03-01 08:06 UTC by StephanZahariev

# Description

## What

GET to return the latest version

## Why

[UPPSF-2104](https://financialtimes.atlassian.net/browse/UPPSF-2104)

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [X] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-03-04 12:19 UTC, gotha requested changes

2021-03-04 12:19 UTC, gotha commented on pkg/resources/patch.go
> +		schemaRevision := r.Header.Get(ContentRevisionHeader)
revision should always  be generated

2021-03-04 12:19 UTC, gotha commented on pkg/resources/patch.go
> +		w.Header().Add(SchemaVersionHeader, schemaVersion)
I am not sure why are we returning the version header here. 
If anything, it makes more sense to return the revision

2021-03-04 12:19 UTC, gotha commented on pkg/resources/utils.go
>  func obtainTxID(req *http.Request) string {
I think here we should use transactionidutils.GetTransactionIDFromRequest and get rid of the txHeaderKey constant

2021-03-04 12:19 UTC, gotha commented on pkg/resources/write.go
> +			fmt.Sprintf("Successfully saved, collection=%s, origin-system-id=%s schema-version=%s", collectionID, originSystemIDHeader, schemaVersion))
just suggestion for improvement. instead of using fmt.Sprintf, we can use log.WithField("collection", "value"), etc. ..

2021-03-05 14:46 UTC, gotha approved these changes

2021-03-08 09:00 UTC, rnov approved these changes

2021-03-08 11:29 UTC, merged